alter table prescriptions
  add column if not exists patient_id uuid references patients(id),
  add column if not exists medication text,
  add column if not exists generic_name text,
  add column if not exists strength text,
  add column if not exists dosage text,
  add column if not exists frequency text,
  add column if not exists duration text,
  add column if not exists quantity integer,
  add column if not exists refills integer default 0,
  add column if not exists refills_remaining integer default 0,
  add column if not exists instructions text,
  add column if not exists indications text,
  add column if not exists status text,
  add column if not exists prescribed_by text,
  add column if not exists prescribed_at timestamp,
  add column if not exists filled_at timestamp,
  add column if not exists expires_at timestamp,
  add column if not exists pharmacy text,
  add column if not exists notes text,
  add column if not exists interactions jsonb default '[]'::jsonb,
  add column if not exists side_effects jsonb default '[]'::jsonb,
  add column if not exists diagnosis text,
  add column if not exists priority text,
  add column if not exists is_emergency boolean default false,
  add column if not exists valid_until timestamp;

alter table prescription_items
  add column if not exists medication_id uuid,
  add column if not exists generic_name text,
  add column if not exists strength text,
  add column if not exists frequency text,
  add column if not exists quantity integer,
  add column if not exists instructions text,
  add column if not exists refills integer default 0,
  add column if not exists is_prn boolean default false,
  add column if not exists route text;
